#!/bin/sh

alias grep='rg --color=auto'

alias ls='ls --color=auto'
alias ll='ls -lav --ignore=..'   # show long listing of all except ".."
alias la='ls -a --ignore=..'   # show listing of all except ".."
alias l='ls -a --ignore=..'   

alias nv='nvim'
alias v='nvim'
alias vim='nvim'
alias e='nvim'
alias emacs='nvim'
alias :q="exit"
alias :x="exit"

alias projects='cd ~/Desktop/Projects'
alias rocketry='cd ~/Desktop/Projects/Rocketry'

alias tm="tmux -2 attach-session || tmux -2 new-session"
alias sc="screen -r || screen"
alias swap="cd /home/elias/.local/state/nvim/swap"
alias eceuw="ssh -X ekountou@129.97.92.188"
alias toECEUW="scp $1 ekountou@129.97.92.188:~/"
alias nvimECEUW="vim scp://ekountou@129.97.92.188//home/ekountou/"

acp () {
	read "REPLY?Are you sure? [y/N] "
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		if [ $# -eq 0 ]; then
			echo "No commit message"
			exit -1
		fi
		git add .
		git commit -m "$1"
		git push
		echo "Commited with message '$1'"
	fi
}
