#!/bin/sh
alias sudo="sudo "

alias grep='rg --color=auto'

alias ls='ls --color=auto'
alias ll='ls -lav --ignore=..'   # show long listing of all except ".."
alias la='ls -a --ignore=..'   # show listing of all except ".."
alias l='ls -a --ignore=..'   

alias nv='nvim'
alias v='nvim'
alias vim='nvim'
alias e='nvim'
alias emacs='nvim'
alias :q="exit"
alias :x="exit"

alias tm="tmux -2 attach-session || tmux -2 new-session"
alias sc="screen -r || screen"
alias swap="cd /home/elias/.local/state/nvim/swap"
alias eceuw="ssh -X ekountou@ecetesla1.uwaterloo.ca"
alias eceJane="ssh -X ekountou@jane.uwaterloo.ca"
alias eceMnt="sshfs -o allow_other,reconnect,ServerAliveInterval=30 ekountou@ecetesla1.uwaterloo.ca:/home/ekountou/ $1"
alias janeMnt="sshfs -o allow_other,reconnect,ServerAliveInterval=30 ekountou@jane.uwaterloo.ca:/zfsspare/ekountou/COFFE/ $1"
alias toECEUW="scp $1 ekountou@ecetesla1.uwaterloo.caa:~/"
alias toOracle="scp -i ~/.ssh/oracle.key $1 opc@140.238.129.239:~/"
alias nvimECEUW="vim scp://ekountou@ecetesla1.uwaterloo.ca//home/ekountou/"
alias oracle="kitty +kitten ssh -i ~/.ssh/oracle.key opc@140.238.129.239"

acp() {
	read "REPLY?Are you sure? [y/N] "
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		if [ $# -eq 0 ]; then
			echo "No commit message"
			exit -1
		fi
		git add .
		git commit -m "$1"
		git push
		echo "Commited with message '$1'"
	fi
}

set -o vi
