# basic stuff
export ZSH="$HOME/.oh-my-zsh"
export PATH=$HOME/bin:/usr/local/bin:$PATH
export EDITOR='nvim'
export DISPLAY="xterm"
export TERM="xterm-256color"

# sourcing
source $HOME/.aliases

# zsh config
ZSH_THEME="robbyrussell"
plugins=(git)

# Needs to be last line
source $ZSH/oh-my-zsh.sh

# Created by `pipx` on 2024-05-13 15:20:27
export PATH="$PATH:/Users/elias/.local/bin"
