# basic stuff
export ZSH="$HOME/.oh-my-zsh"
export PATH=$HOME/bin:/usr/local/bin:$PATH
export EDITOR='nvim'

# sourcing
source $HOME/.aliases
source $HOME/.keys

# zsh config
ZSH_THEME="robbyrussell"
plugins=(git ripgrep)

# Needs to be last line
source $ZSH/oh-my-zsh.sh
